# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fr_R_cpp <- function(x, y, R) {
    .Call(`_fourier_fr_R_cpp`, x, y, R)
}

fr_R_cpp_vec <- function(x, y, R) {
    .Call(`_fourier_fr_R_cpp_vec`, x, y, R)
}

fr_Rm_cpp <- function(x, y, R) {
    .Call(`_fourier_fr_Rm_cpp`, x, y, R)
}

